[project]
name = "data-dashboard-crew"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai>=1.9.3",
    "crewai-tools>=1.9.3",
    "pandas>=3.0.0",
]
